// Get Posts
export const POSTS_LOADING = 'POSTS_LOADING';
export const POSTS_LOADED = 'POSTS_LOADED';
export const POSTS_ERROR = 'POSTS_ERROR';

// Get Single Post
export const SINGLE_POST_LOADING = 'SINGLE_POST_LOADING';
export const SINGLE_POST_LOADED = 'SINGLE_POST_LOADED';
export const SINGLE_POST_ERROR = 'SINGLE_POST_ERROR';

// Create Post
export const CREATED_POST_LOADING = 'CREATE_POST_LOADING';
export const CREATED_POST_LOADED = 'CREATE_POST_LOADED';
export const CREATED_POST_ERROR = 'CREATE_POST_ERROR';